#!/usr/bin/env bash
# ============================================================================
# run_table5.sh -- one-command reproduction of PermNet-RM paper Table 5.
#
# Records toolchain versions, rebuilds both encoder binaries, runs ELMO on
# each, runs the analysis script, and saves a textual summary. Intended to
# be run from the elmo/ directory.
#
# Usage:
#     cd elmo/
#     ./run_table5.sh
# ============================================================================
set -euo pipefail

# Always run from the directory the script lives in so relative paths work.
cd "$(dirname "$0")"

VERSIONS="versions.txt"
TABLE5="table5.txt"
PLOTS_DIR="plots"

ELMO_TOOL_DIR="../elmo_tool"
ELMO_BIN="${ELMO_TOOL_DIR}/elmo"

# ---------------------------------------------------------------------------
# 0. Sanity checks on prerequisites.
# ---------------------------------------------------------------------------
need() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "ERROR: required tool '$1' not found in PATH." >&2
        exit 2
    }
}
need arm-none-eabi-gcc
need make
need python3

if [[ ! -d "${ELMO_TOOL_DIR}" ]]; then
    echo "ERROR: ELMO is not installed at ${ELMO_TOOL_DIR}." >&2
    echo "Clone https://github.com/sca-research/ELMO.git there and build it," >&2
    echo "or see elmo/README.md for the pinned commit." >&2
    exit 2
fi
if [[ ! -x "${ELMO_BIN}" ]]; then
    echo "ERROR: ELMO binary ${ELMO_BIN} is missing or not executable." >&2
    echo "Build it once: (cd ${ELMO_TOOL_DIR} && make)" >&2
    exit 2
fi

# ---------------------------------------------------------------------------
# 1. Record the full toolchain version footprint into versions.txt.
# ---------------------------------------------------------------------------
echo "Recording toolchain versions -> ${VERSIONS}"
{
    echo "# PermNet-RM / ELMO reproduction -- toolchain snapshot"
    echo "# Generated by run_table5.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# Host:      $(uname -a)"
    echo
    echo "--- arm-none-eabi-gcc ---"
    arm-none-eabi-gcc --version | head -n 1
    echo
    echo "--- make ---"
    make --version | head -n 1
    echo
    echo "--- python3 ---"
    python3 --version
    echo
    echo "--- numpy ---"
    python3 -c 'import numpy, sys; print(numpy.__version__)' 2>&1 || echo "(numpy missing)"
    echo
    echo "--- matplotlib (optional) ---"
    python3 -c 'import matplotlib, sys; print(matplotlib.__version__)' 2>&1 || echo "(matplotlib missing; plots will be skipped)"
    echo
    echo "--- ELMO ---"
    if [[ -d "${ELMO_TOOL_DIR}/.git" ]]; then
        (cd "${ELMO_TOOL_DIR}" && git log -1 --pretty='%H %s' 2>&1 || true)
        (cd "${ELMO_TOOL_DIR}" && git status --porcelain 2>&1 | head -n 20 || true) \
            | sed 's/^/  dirty? /'
    else
        echo "(elmo_tool is present but is not a git checkout)"
    fi
    echo
    echo "--- ELMO binary ---"
    ls -la "${ELMO_BIN}"
} | tee "${VERSIONS}"

echo

# ---------------------------------------------------------------------------
# 2. Clean + rebuild the Thumb binaries.
# ---------------------------------------------------------------------------
echo "=== Rebuilding PermNet-RM and BIT0MASK binaries for Cortex-M0 ==="
make clean
make

# ---------------------------------------------------------------------------
# 3. Run ELMO on each binary.
# ---------------------------------------------------------------------------
echo
echo "=== Running ELMO simulation on both encoders ==="
make run

# ---------------------------------------------------------------------------
# 4. Run the analysis.
# ---------------------------------------------------------------------------
PERMNET_TRACES="output_permnet/output/traces"
BITMASK_TRACES="output_bitmask/output/traces"
MASKED_TRACES="output_masked/output/traces"

for d in "${PERMNET_TRACES}" "${BITMASK_TRACES}" "${MASKED_TRACES}"; do
    if [[ ! -d "$d" ]]; then
        echo "ERROR: expected trace directory $d not produced by ELMO run." >&2
        exit 3
    fi
done

echo
echo "=== Running analyze_traces.py -- PermNet-RM vs BIT0MASK ==="
mkdir -p "${PLOTS_DIR}"
: > "${TABLE5}"
{
    echo "######################################################################"
    echo "#  Comparison 1: unmasked PermNet-RM  vs  BIT0MASK baseline"
    echo "#  (this is the paper's Table 5)"
    echo "######################################################################"
    python3 analyze_traces.py "${PERMNET_TRACES}" "${BITMASK_TRACES}" \
            "${PLOTS_DIR}/permnet_vs_bitmask" \
            "PermNet-RM (unmasked)" "BIT0MASK (vulnerable baseline)" \
        || echo "[analysis returned non-zero; see log above]"
} | tee -a "${TABLE5}"

echo
echo "=== Running analyze_traces.py -- masked d=1 vs BIT0MASK ==="
{
    echo
    echo "######################################################################"
    echo "#  Comparison 2: masked d=1 PermNet-RM  vs  BIT0MASK baseline"
    echo "#  (shows attack-relevant signal reduction under a fresh share)"
    echo "######################################################################"
    python3 analyze_traces.py "${MASKED_TRACES}" "${BITMASK_TRACES}" \
            "${PLOTS_DIR}/masked_vs_bitmask" \
            "PermNet-RM masked d=1" "BIT0MASK (vulnerable baseline)" \
        || echo "[analysis returned non-zero; see log above]"
} | tee -a "${TABLE5}"

echo
echo "=== Running analyze_traces.py -- masked d=1 vs unmasked PermNet-RM ==="
{
    echo
    echo "######################################################################"
    echo "#  Comparison 3: masked d=1 PermNet-RM  vs  unmasked PermNet-RM"
    echo "#  (does masking further reduce residual leakage on Cortex-M0?)"
    echo "######################################################################"
    python3 analyze_traces.py "${MASKED_TRACES}" "${PERMNET_TRACES}" \
            "${PLOTS_DIR}/masked_vs_permnet" \
            "PermNet-RM masked d=1" "PermNet-RM (unmasked)" \
        || echo "[analysis returned non-zero; see log above]"
} | tee -a "${TABLE5}"

# ---------------------------------------------------------------------------
# 5. Summary.
# ---------------------------------------------------------------------------
echo
echo "=== Reproduction complete ==="
echo "    Toolchain snapshot:  ${VERSIONS}"
echo "    Table 5 numbers:     ${TABLE5}"
echo "    Plots:               ${PLOTS_DIR}/"
echo
echo "Compare values in ${TABLE5} against paper Section 5, Table 5. Any"
echo "numerical drift vs the paper points to a toolchain-version delta --"
echo "check versions.txt against the pinned ELMO commit in elmo/README.md."
